version: "3.9"

services:
  bd-simf:
    image: bd-simf:latest
    hostname: bd-simf
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD_FILE: /run/secrets/postgre_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    secrets:
      - postgre_password
    configs:
      - source: creacionbd1
        target: /var/lib/postgresql/1_Creacion_inicial_simf_simfhisto.sql
      - source: creacionbd2
        target: /var/lib/postgresql/2_creacion_jobs.sql
      - source: creacionbd3
        target: /var/lib/postgresql/3_Usuario_GS_consulta_simf.sql
      - source: creacionbd4
        target: /var/lib/postgresql/4_Creacion_vw_status_jobs_simf.sql
      - source: creacionbd5
        target: /var/lib/postgresql/crear_user_pgagent.sql
      - source: creacionbd6
        target: /var/lib/postgresql/pg_hba.conf
      - source: creacionbd7
        target: /var/lib/postgresql/postgresql.conf
      - source: creacionbd8
        target: /var/lib/postgresql/tb_transferencia_parametros.sql
      - source: creacionbd9
        target: /var/lib/postgresql/borrar_transac_id_simf.sql
      - source: failover
        target: /var/lib/postgresql/failover.sh
        mode: 0775
      - source: ordenbd
        target: /docker-entrypoint-initdb.d/orden-bd.sh
        mode: 0775
    ports:
      - target: 5432
        published: 5445
        protocol: tcp
        mode: host
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
            size: 1073741824
      - pgdata_simf:/var/lib/postgresql/data/pgdata
      - /tblspc_historico/simf/simf_hist:/tblspc_historico/simf/simf_hist
      - /tblspc_transaccional/simf/simf_data:/tblspc_transaccional/simf/simf_data
      - /tblspc_vistas/simf/simf_view:/tblspc_vistas/simf/simf_view
      - /tblspc_vistas/simf/simf_logs:/tblspc_vistas/simf/simf_logs
      - /tblspc_transaccional/simf/simf_idx:/tblspc_transaccional/simf/simf_idx
      - /tblspc_historico/sglbtr/sglbtr_hist:/tblspc_historico/sglbtr/sglbtr_hist
      - /tblspc_transaccional/sglbtr/sglbtr_data:/tblspc_transaccional/sglbtr/sglbtr_data
      - /tblspc_vistas/sglbtr/sglbtr_view:/tblspc_vistas/sglbtr/sglbtr_view
      - /tblspc_vistas/sglbtr/sglbtr_logs:/tblspc_vistas/sglbtr/sglbtr_logs
      - /tblspc_transaccional/sglbtr/sglbtr_idx:/tblspc_transaccional/sglbtr/sglbtr_idx
      - /backups/:/backups/
      - /logs/postgres_logs:/logs/postgres_logs
    networks:
      - pg_net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '8' ##Ajustar para 8 cpu 4 | y para 12 cpu 6
          memory: 8192M ##Ajustr segun sea el caso;para 24GB 6144, para 32GB 8192, para 512GB 131072M
        reservations:
          memory: 4096M ##Ajustr segun sea el caso;para 24GB 3072, para 32GB 4096, para 512GB 65536M
      replicas: 1
      placement:
        constraints:
          - node.labels.pg_role == primary
      restart_policy:
        condition: on-failure
      endpoint_mode: dnsrr
    # =========================================================================
    # COMANDO CONFIGURADO CON PARÁMETROS NATIVOS PARA SALIDA JSON
    # =========================================================================
    command: >
      bash -c "./docker-entrypoint-initdb.d/orden-bd.sh 
      -c log_destination=jsonlog 
      -c logging_collector=off 
      -c log_min_messages=info"

  primary-exporter:
    image: prometheuscommunity/postgres-exporter:v0.17.1
    environment:
      DATA_SOURCE_NAME: "postgresql://simf_admin_user:simf@tasks.bd-simf_bd-simf:5432/postgres?sslmode=disable&connect_timeout=5"
    networks:
      - pg_net
    ports:
      - target: 9187
        published: 9187
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.pg_role == primary
      labels:
        prometheus.scrape: "true"
        prometheus.port: "9187"
        pg_role: "primary"

networks:
  pg_net:
    external: true
volumes:
  pgdata_simf:
    external: true
secrets:
  postgre_password:
    external: true
configs:
  creacionbd1:
    file: /app_psql/packague_bd/creacion-bd/1_Creacion_inicial_simf_simfhisto.sql
  creacionbd2:
    file: /app_psql/packague_bd/creacion-bd/2_creacion_jobs.sql
  creacionbd3:
    file: /app_psql/packague_bd/creacion-bd/3_Usuario_GS_consulta_simf.sql
  creacionbd4:
    file: /app_psql/packague_bd/creacion-bd/4_Creacion_vw_status_jobs_simf.sql
  creacionbd5:
    file: /app_psql/packague_bd/creacion-bd/crear_user_pgagent.sql
  creacionbd6:
    file: /app_psql/packague_bd/creacion-bd/pg_hba.conf
  creacionbd7:
    file: /app_psql/packague_bd/creacion-bd/postgresql.conf
  creacionbd8:
    file: /app_psql/packague_bd/creacion-bd/tb_transferencia_parametros.sql
  creacionbd9:
    file: /app_psql/packague_bd/creacion-bd/borrar_transac_id_simf.sql
  failover:
    file: /app_psql/packague_bd/failover.sh
  ordenbd:
    file: /app_psql/packague_bd/orden-bd.sh
