version: '3.8'

services:
  replica:
    image: ibp_simf_replica
    hostname: bd-simf-{{.Task.Slot}}
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - target: 5432
        published: 5445
        protocol: tcp
        mode: host
    configs:
      - source: failover2
        target: /docker-entrypoint-initdb.d/failover.sh
        mode: 0775
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
            size: 1073741824

      - pgdata_simf:/var/lib/postgresql/data/pgdata
      - /tblspc_historico/simf/simf_hist:/tblspc_historico/simf/simf_hist
      - /tblspc_transaccional/simf/simf_data:/tblspc_transaccional/simf/simf_data
      - /tblspc_vistas/simf/simf_view:/tblspc_vistas/simf/simf_view
      - /tblspc_vistas/simf/simf_logs:/tblspc_vistas/simf/simf_logs
      - /tblspc_transaccional/simf/simf_idx:/tblspc_transaccional/simf/simf_idx
      - /tblspc_historico/sglbtr/sglbtr_hist:/tblspc_historico/sglbtr/sglbtr_hist
      - /tblspc_transaccional/sglbtr/sglbtr_data:/tblspc_transaccional/sglbtr/sglbtr_data
      - /tblspc_vistas/sglbtr/sglbtr_view:/tblspc_vistas/sglbtr/sglbtr_view
      - /tblspc_vistas/sglbtr/sglbtr_logs:/tblspc_vistas/sglbtr/sglbtr_logs
      - /tblspc_transaccional/sglbtr/sglbtr_idx:/tblspc_transaccional/sglbtr/sglbtr_idx
      - /backups/:/backups/
    networks:
      - pg_net
    # =========================================================================
    # COMANDO CONFIGURADO CON PARÁMETROS NATIVOS PARA SALIDA JSON
    # =========================================================================
    command: >
      bash -c "./docker-entrypoint-initdb.d/failover.sh"
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.pg_role == replica
      restart_policy:
        condition: on-failure
      endpoint_mode: dnsrr

  replica-exporter:
    image: prometheuscommunity/postgres-exporter:v0.17.1
    environment:
      DATA_SOURCE_NAME: "postgresql://simf_admin_user:simf@bd-simf-{{.Task.Slot}}:5432/postgres?sslmode=disable&connect_timeout=10"
    networks:
      - pg_net
    labels:
      prometheus.scrape: "true"
      prometheus.port: "9187"

    ports:
      - target: 9187
        published: 9187 
        protocol: tcp
        mode: host
    deploy:
      resources:
        limits:
          cpus: '4' ##Ajustar para 8 cpu 4 | y para 12 cpu 6
          memory: 6144M ##Ajustr segun sea el caso;para 24GB 6144, para 32GB 8192, para 512GB 131072M
        reservations:
          memory: 3072M ##Ajustr segun sea el caso;para 24GB 3072, para 32GB 4096, para 512GB 65536M

      replicas: 2
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.pg_role == replica
      labels:
        prometheus.scrape: "true"
        prometheus.port: "9187"
        pg_role: "replica"

volumes:
  pgdata_simf:
    external: true
networks:
  pg_net:
    external: true
configs:
  failover2:
    file: /app_psql/packague_bd/failover.sh
