version: '3.8'

x-templates:
  deploy-base: &default_deploy
    mode: replicated
    replicas: 2
    endpoint_mode: dnsrr
    placement:
      max_replicas_per_node: 1
      constraints:
       # - "node.labels. == microservices"
        - node.labels.pg_role == replica
    restart_policy:
      condition: on-failure
      delay: 3s
      max_attempts: 3
      window: 100s
    update_config:
      parallelism: 1
      order: stop-first
      failure_action: rollback
      monitor: 30s
    rollback_config:
      parallelism: 0
      order: stop-first

  env-base: &env-base
    TZ: America/Caracas

  networks-base: &networks-base
    - pg_net
    - kafka_kafka-net
    - nginx_lbnet

  config-rest-base: &config-rest-base
    - '/app_services/app_sglpar/rest_api/:/app/config'

  config-inter-base: &config-inter-base
    - '/app_services/app_sglpar/inter/:/app/config'

  config-intra-base: &config-intra-base
    - '/app_services/app_sglpar/intra/:/app/config'

  config-efectivo-base: &config-efectivo-base
    - '/app_services/app_sglpar/efectivo/:/app/config'

  config-common-base: &config-common-base
    - '/app_services/app_sglpar/comunes/:/app/config'

  extra-host-base: &extra-host-base
    - "efectivo.lbtr:172.24.199.200"
    - "inter.lbtr:172.24.199.200"
    - "intra.lbtr:172.24.199.200"
    - "rest_api.simf:172.24.199.200"

services:
  rest_api:
    image: 'sycom/sglpar_rest_api:0.2.4'
    hostname: '{{.Service.Name}}-{{.Task.Slot}}'
    ports:
      - target: 8083
        published: 8083
        protocol: tcp
        mode: host
    volumes: *config-rest-base
    environment: *env-base
    networks: *networks-base
    labels:
      - "description=Rest API SGLPAR - Payment"
      - "prometheus_scrape=true"
      - "prometheus_port=8083"
    extra_hosts: *extra-host-base
    deploy:
      <<: *default_deploy
      labels:
        description: "Rest API SGLPAR - Payment"

  # --- SERVICIOS INTRA ---
  intra_emi:
    image: 'sycom/sglpar_ms:0.2.3'
    hostname: '{{.Service.Name}}-{{.Task.Slot}}'
    command: ["--ms", "MSFitofiCdtrTrfBcoEmi", "--id", "1", "--port", "9305", "--tp", "intra"]
    ports:
      - target: 9305
        published: 9305
        protocol: tcp
        mode: host
    volumes: *config-intra-base
    environment: *env-base
    networks: *networks-base
    labels:
      - "description=MS Intra - Fitofi Cdtr Trf Bco Emi"
      - "prometheus_scrape=true"
      - "prometheus_port=9305"
    extra_hosts: *extra-host-base
    deploy:
      <<: *default_deploy
      labels:
        description: "MS Intra - Fitofi Cdtr Trf Bco Emi"

  intra_sts_emi:
    image: 'sycom/sglpar_ms:0.2.3'
    hostname: '{{.Service.Name}}-{{.Task.Slot}}'
    command: ["--ms", "MSFitofiCdtrTrfStsRptBcoEmi", "--id", "1", "--port", "9306", "--tp", "intra"]
    ports:
      - target: 9306
        published: 9306
        protocol: tcp
        mode: host
    volumes: *config-intra-base
    environment: *env-base
    networks: *networks-base
    labels:
      - "description=MS Intra - Fitofi Cdtr Trf Sts Rpt Bco Emi"
      - "prometheus_scrape=true"
      - "prometheus_port=9306"
    extra_hosts: *extra-host-base
    deploy:
      <<: *default_deploy
      labels:
        description: "MS Intra - Fitofi Cdtr Trf Sts Rpt Bco Emi"

  intra_sts_rec:
    image: 'sycom/sglpar_ms:0.2.3'
    hostname: '{{.Service.Name}}-{{.Task.Slot}}'
    command: ["--ms", "MSFitofiCdtrTrfStsRptBcoRec", "--id", "1", "--port", "9307", "--tp", "intra"]
    ports:
      - target: 9307
        published: 9307
        protocol: tcp
        mode: host
    volumes: *config-intra-base
    environment: *env-base
    networks: *networks-base
    labels:
      - "description=MS Intra - Fitofi Cdtr Trf Sts Rpt Bco Rec"
      - "prometheus_scrape=true"
      - "prometheus_port=9307"
    extra_hosts: *extra-host-base
    deploy:
      <<: *default_deploy
      labels:
        description: "MS Intra - Fitofi Cdtr Trf Sts Rpt Bco Rec"

  # --- SERVICIOS INTER ---
  inter_emi:
    image: 'sycom/sglpar_ms:0.2.3'
    hostname: '{{.Service.Name}}-{{.Task.Slot}}'
    command: ["--ms", "MSCstmrCdtrTrfBcoEmi", "--id", "1", "--port", "9301", "--tp", "inter"]
    ports:
      - target: 9301
        published: 9301
        protocol: tcp
        mode: host
    volumes: *config-inter-base
    environment: *env-base
    networks: *networks-base
    labels:
      - "description=MS Inter - Cstmr Cdtr Trf Bco Emi"
      - "prometheus_scrape=true"
      - "prometheus_port=9301"
    extra_hosts: *extra-host-base
    deploy:
      <<: *default_deploy
      labels:
        description: "MS Inter - Cstmr Cdtr Trf Bco Emi"

  inter_rec:
    image: 'sycom/sglpar_ms:0.2.3'
    hostname: '{{.Service.Name}}-{{.Task.Slot}}'
    command: ["--ms", "MSCstmrCdtrTrfBcoRec", "--id", "1", "--port", "9302", "--tp", "inter"]
    ports:
      - target: 9302
        published: 9302
        protocol: tcp
        mode: host
    volumes: *config-inter-base
    environment: *env-base
    networks: *networks-base
    labels:
      - "description=MS Inter - Cstmr Cdtr Trf Bco Rec"
      - "prometheus_scrape=true"
      - "prometheus_port=9302"
    extra_hosts: *extra-host-base
    deploy:
      <<: *default_deploy
      labels:
        description: "MS Inter - Cstmr Cdtr Trf Bco Rec"

  inter_sts_emi:
    image: 'sycom/sglpar_ms:0.2.3'
    hostname: '{{.Service.Name}}-{{.Task.Slot}}'
    command: ["--ms", "MSCstmrCdtrTrfBcoEmiStsRpt", "--id", "1", "--port", "9303", "--tp", "inter"]
    ports:
      - target: 9303
        published: 9303
        protocol: tcp
        mode: host
    volumes: *config-inter-base
    environment: *env-base
    networks: *networks-base
    labels:
      - "description=MS Inter - Cstmr Cdtr Trf Bco Emi Sts Rpt"
      - "prometheus_scrape=true"
      - "prometheus_port=9303"
    extra_hosts: *extra-host-base
    deploy:
      <<: *default_deploy
      labels:
        description: "MS Inter - Cstmr Cdtr Trf Bco Emi Sts Rpt"

  inter_sts_rec:
    image: 'sycom/sglpar_ms:0.2.3'
    hostname: '{{.Service.Name}}-{{.Task.Slot}}'
    command: ["--ms", "MSCstmrCdtrTrfBcoRecStsRpt", "--id", "1", "--port", "9304", "--tp", "inter"]
    ports:
      - target: 9304
        published: 9304
        protocol: tcp
        mode: host
    volumes: *config-inter-base
    environment: *env-base
    networks: *networks-base
    labels:
      - "description=MS Inter - Cstmr Cdtr Trf Bco Rec Sts Rpt"
      - "prometheus_scrape=true"
      - "prometheus_port=9304"
    extra_hosts: *extra-host-base
    deploy:
      <<: *default_deploy
      labels:
        description: "MS Inter - Cstmr Cdtr Trf Bco Rec Sts Rpt"

  efectivo_emi:
    image: 'sycom/sglpar_ms:0.2.3'
    hostname: '{{.Service.Name}}-{{.Task.Slot}}'
    command: ["--ms", "MSFitofiCdtrTrfBcoEmiEfectivo", "--id", "1", "--port", "9701", "--tp", "efectivo"]
    ports:
      - target: 9701
        published: 9701
        protocol: tcp
        mode: host
    volumes: *config-efectivo-base
    environment: *env-base
    networks: *networks-base
    labels:
      - "description=MS Efectivo - Fitofi Cdtr Trf Bco Emi"
      - "prometheus_scrape=true"
      - "prometheus_port=9701"
    extra_hosts: *extra-host-base
    deploy:
      <<: *default_deploy
      labels:
        description: "MS Efectivo - Fitofi Cdtr Trf Bco Emi"

  efectivo_rec:
    image: 'sycom/sglpar_ms:0.2.3'
    hostname: '{{.Service.Name}}-{{.Task.Slot}}'
    command: ["--ms", "MSFitofiCdtrTrfBcoRecEfectivo", "--id", "1", "--port", "9702", "--tp", "efectivo"]
    ports:
      - target: 9702
        published: 9702
        protocol: tcp
        mode: host
    volumes: *config-efectivo-base
    environment: *env-base
    networks: *networks-base
    labels:
      - "description=MS Efectivo - Fitofi Cdtr Trf Bco Rec"
      - "prometheus_scrape=true"
      - "prometheus_port=9702"
    extra_hosts: *extra-host-base
    deploy:
      <<: *default_deploy
      labels:
        description: "MS Efectivo - Fitofi Cdtr Trf Bco Rec"

  efectivo_sts_emi:
    image: 'sycom/sglpar_ms:0.2.3'
    hostname: '{{.Service.Name}}-{{.Task.Slot}}'
    command: ["--ms", "MSFitofiCdtrTrfStsRptBcoEmiEfectivo", "--id", "1", "--port", "9403", "--tp", "efectivo"]
    ports:
      - target: 9403
        published: 9403
        protocol: tcp
        mode: host
    volumes: *config-efectivo-base
    environment: *env-base
    networks: *networks-base
    labels:
      - "description=MS Efectivo - Fitofi Cdtr Trf Sts Rpt Bco Emi"
      - "prometheus_scrape=true"
      - "prometheus_port=9403"
    extra_hosts: *extra-host-base
    deploy:
      <<: *default_deploy
      labels:
        description: "MS Efectivo - Fitofi Cdtr Trf Sts Rpt Bco Emi"

  reproceso:
    image: 'sycom/sglpar_ms:0.2.3'
    hostname: '{{.Service.Name}}-{{.Task.Slot}}'
    command: ["--ms", "MSReprocesoSGLBTR", "--id", "1", "--port", "9410", "--tp", "comunes_lbtr"]
    ports:
      - target: 9410
        published: 9410
        protocol: tcp
        mode: host
    volumes: *config-common-base
    environment: *env-base
    networks: *networks-base
    labels:
      - "description=MS Comunes - Reproceso SGLBTR"
      - "prometheus_scrape=true"
      - "prometheus_port=9410"
    extra_hosts: *extra-host-base
    deploy:
      <<: *default_deploy
      labels:
        description: "MS Comunes - Reproceso SGLBTR"

  notificaciones:
    image: 'sycom/sglpar_ms:0.2.3'
    hostname: '{{.Service.Name}}-{{.Task.Slot}}'
    command: ["--ms", "MSMultiservicioSGLBTR", "--id", "1", "--port", "9411", "--tp", "comunes_lbtr"]
    ports:
      - target: 9411
        published: 9411
        protocol: tcp
        mode: host
    volumes: *config-common-base
    environment: *env-base
    networks: *networks-base
    labels:
      - "description=MS Comunes - Multiservicio SGLBTR"
      - "prometheus_scrape=true"
      - "prometheus_port=9411"
    extra_hosts: *extra-host-base
    deploy:
      <<: *default_deploy
      labels:
        description: "MS Comunes - Multiservicio SGLBTR"

networks:
  pg_net:
    external: true
  kafka_kafka-net:
    external: true
  nginx_lbnet:
    external: true
